"""
main.py — Copilot Service Entry Point
======================================
Starts the FastAPI application for the AI Copilot (RAG) service.

Usage:
    # From the services/copilot/ directory:
    uvicorn main:app --reload --port 8001

    # Interactive API docs (auto-generated by FastAPI):
    http://localhost:8001/docs
"""

import os
import sys

# Make the shared/ package importable when running from services/copilot/
_PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from api.routes import router
from api.tenant_routes import router as tenant_router

app = FastAPI(
    title="AI Copilot Service",
    description=(
        "Upload your business data and ask natural language questions. "
        "Answers are grounded in your documents using Retrieval Augmented Generation (RAG)."
    ),
    version="0.1.0",
)

# CORS — allows a browser-based frontend to call this API.
# In production, replace ['*'] with your actual frontend domain(s).
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(tenant_router)
app.include_router(router)
